name: Python CI

on:
  push:
    branches:
      - main 
      - master

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - 3.12  # specify the Python versions you want to test against

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        pytest commonpasswords/
